AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cxp-sam-get-upstream-java-sync

  Sample SAM Template for cxp-sam-get-upstream-java-sync

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  CxpSamGetUpstreamJavaSyncFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      MemorySize: 1024
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
          CXP_DOWNSTREAM_FUNCTION_NAME: "arn:aws:lambda:eu-west-1:005913962162:function:cxp-sam-get-downstream-ja-CxpSamGetDownstreamJavaF-UaspRGJei3GV"
      Events:
        HelloWorld:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /cxp-sam-get-upstream-java-sync/upstream
            Method: get
            ApiId: !Ref CxpSamGetUpstreamJavaSyncHttpApi
      Policies:
        - LambdaInvokePolicy:
            FunctionName: "cxp-sam-get-downstream-ja-CxpSamGetDownstreamJavaF-UaspRGJei3GV"
    Metadata:
      DockerTag: java11-maven-v1
      DockerContext: ./UpStreamFunction
      Dockerfile: Dockerfile
  # In order to create the authorizers properly we have to use an explicit HttpApi resource
  CxpSamGetUpstreamJavaSyncHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        DefaultAuthorizer: OpenIdAuth
        Authorizers:
          OpenIdAuth:
            AuthorizationScopes:
              - profile
              - email
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: "https://oidc.cloudtrain.aws.msgoat.eu/auth/realms/CloudExpertProgram"
              audience:
                - account
                - cxp-serverless-tester
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UpStreamApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${CxpSamGetUpstreamJavaSyncHttpApi}.execute-api.${AWS::Region}.amazonaws.com/cxp-sam-get-upstream-java-sync/upstream"
  UpStreamFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt CxpSamGetUpstreamJavaSyncFunction.Arn
  UpStreamFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CxpSamGetUpstreamJavaSyncFunctionRole.Arn
